# Generated by Django 4.1 on 2024-02-01 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='letters',
            new_name='correct_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_finished',
        ),
    ]
