# Generated by Django 4.1 on 2024-02-03 12:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_letters_word_correct_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='bought',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), default=list, size=None),
        ),
    ]
