# Generated by Django 4.2.3 on 2023-08-19 17:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='attempts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), default=list, size=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='word',
            field=models.CharField(default='hello', max_length=150),
            preserve_default=False,
        ),
    ]
