# Generated by Django 4.2.3 on 2023-09-07 10:10

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_attempts_profile_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_profile', models.BooleanField(default=True)),
                ('show_stats', models.BooleanField(default=True)),
                ('show_balance', models.BooleanField(default=True)),
                ('notifications', models.BooleanField(default=True)),
                ('ads', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='coins',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='gps',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='letters',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='word',
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=15)),
                ('date', models.DateField(default=datetime.date.today)),
                ('letters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), default=list, size=None)),
                ('wrong_attempts', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), default=list, size=None)),
                ('found', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='settings',
            field=models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='account.settings'),
            preserve_default=False,
        ),
    ]
