# Generated by Django 4.2.3 on 2023-09-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_settings_rename_coins_profile_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='words',
        ),
    ]
