# Generated by Django 4.2.3 on 2023-09-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_profile_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='settings',
        ),
        migrations.AddField(
            model_name='profile',
            name='ads',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_balance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_profile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_stats',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
