# Generated by Django 4.2.3 on 2023-07-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_profile_words_profile_words'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word',
        ),
    ]
